Repository GSS-FED/vital-ui-kit-react, pull requests merged in 2019-01, with the labels that each got.

#408 Fix types deps
  package.json
  packages/button/package.json
  packages/form/package.json
  packages/list/package.json
  packages/modal/package.json
  packages/theme/package.json
  packages/utils/package.json
  packages/utils/src/box/Box.tsx
  yarn.lock
Labels: internal

#412 Fix checkbox wrap and update package.json
  package.json
  packages/form/src/checkbox/Checkbox.tsx
  packages/form/src/checkbox/__snapshots__/Checkbox.spec.tsx.snap
Labels: bug

#416 Update Select props and all dependencies
  jest.config.js
  package.json
  packages/avatar/package.json
  packages/avatar/src/AvatarBadge.tsx
  packages/badge/package.json
  packages/button/package.json
  packages/card/package.json
  packages/form/package.json
  packages/form/src/checkbox/Checkbox.spec.tsx
  packages/form/src/select/Dropdown.tsx
  packages/form/src/select/Select.tsx
  packages/form/src/slider/Slider.spec.tsx
  packages/icon/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/modal/package.json
  packages/modal/src/Modal.tsx
  packages/pill/package.json
  packages/pill/src/PillsGroup.tsx
  packages/popup/package.json
  packages/tabs/package.json
  packages/theme/package.json
  packages/theme/src/ThemeProvider.spec.tsx
  packages/tooltip/package.json
  packages/tooltip/src/Tooltip.spec.tsx
  packages/tooltip/src/Tooltip.stories.tsx
  packages/tooltip/src/Tooltip.tsx
  packages/tooltip/src/__snapshots__/Tooltip.spec.tsx.snap
  packages/utils/package.json
  packages/utils/src/box/Box.tsx
  packages/web/package.json
  yarn.lock
Labels: internal, version
